#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pciutils
Version  : 3.5.6
Release  : 32
URL      : https://www.kernel.org/pub/software/utils/pciutils/pciutils-3.5.6.tar.xz
Source0  : https://www.kernel.org/pub/software/utils/pciutils/pciutils-3.5.6.tar.xz
Summary  : The PCI Utilities
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: pciutils-bin = %{version}-%{release}
Requires: pciutils-data = %{version}-%{release}
Requires: pciutils-lib = %{version}-%{release}
Requires: pciutils-license = %{version}-%{release}
Requires: pciutils-man = %{version}-%{release}
BuildRequires : pkgconfig(libkmod)
BuildRequires : pkgconfig(zlib)
BuildRequires : systemd-dev
Patch1: 0001-Makefile-build-fixes.patch

%description
This package contains various utilities for inspecting and
setting of devices connected to the PCI bus.

%package bin
Summary: bin components for the pciutils package.
Group: Binaries
Requires: pciutils-data = %{version}-%{release}
Requires: pciutils-license = %{version}-%{release}

%description bin
bin components for the pciutils package.


%package data
Summary: data components for the pciutils package.
Group: Data

%description data
data components for the pciutils package.


%package dev
Summary: dev components for the pciutils package.
Group: Development
Requires: pciutils-lib = %{version}-%{release}
Requires: pciutils-bin = %{version}-%{release}
Requires: pciutils-data = %{version}-%{release}
Provides: pciutils-devel = %{version}-%{release}
Requires: pciutils = %{version}-%{release}

%description dev
dev components for the pciutils package.


%package lib
Summary: lib components for the pciutils package.
Group: Libraries
Requires: pciutils-data = %{version}-%{release}
Requires: pciutils-license = %{version}-%{release}

%description lib
lib components for the pciutils package.


%package license
Summary: license components for the pciutils package.
Group: Default

%description license
license components for the pciutils package.


%package man
Summary: man components for the pciutils package.
Group: Default

%description man
man components for the pciutils package.


%prep
%setup -q -n pciutils-3.5.6
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1565822609
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1565822609
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pciutils
cp COPYING %{buildroot}/usr/share/package-licenses/pciutils/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lspci
/usr/bin/setpci
/usr/bin/update-pciids

%files data
%defattr(-,root,root,-)
/usr/share/pci.ids.gz

%files dev
%defattr(-,root,root,-)
/usr/include/pci/config.h
/usr/include/pci/header.h
/usr/include/pci/pci.h
/usr/include/pci/types.h
/usr/lib64/libpci.so
/usr/lib64/pkgconfig/libpci.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpci.so.3
/usr/lib64/libpci.so.3.5.6

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pciutils/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man7/pcilib.7
/usr/share/man/man8/lspci.8
/usr/share/man/man8/setpci.8
/usr/share/man/man8/update-pciids.8
